### ISSUE TITLE
bug: helm crd defs don't get updated on `make`

### ISSUE THREAD

**Issue by waveywaves** [UffizziCloud/uffizzi-cluster-operator#26]
Currently if the CRD definition for the operator gets updated after a change to the API, the helm chart values need to be changed manually. This can be automated by using yq and copying the values from the operator generated spec to the helm template.

**Comment by axisofentropy** [comment]
How do we generate the spec?

**Comment by waveywaves** [comment]
The make command helps generate the spec from the api defnitions given in golang. Look out for the `make manifests` command

**Comment by waveywaves** [comment]
fixed
